export const DESKTOP_CANVAS_COMMENTS_CARD_WIDTH_PX = 340;
export const DESKTOP_CANVAS_COMMENTS_CARD_RIGHT_OFFSET_PX = 16;
export const DESKTOP_CANVAS_COMMENTS_CARD_TOP_OFFSET_PX = 68;
export const DESKTOP_CANVAS_COMMENTS_CARD_BOTTOM_OFFSET_PX = 54;
export const DESKTOP_CANVAS_COMMENTS_CARD_GUTTER_PX = 16;

export const DESKTOP_CANVAS_COMMENTS_RESERVED_WIDTH_PX =
    DESKTOP_CANVAS_COMMENTS_CARD_WIDTH_PX +
    DESKTOP_CANVAS_COMMENTS_CARD_RIGHT_OFFSET_PX +
    DESKTOP_CANVAS_COMMENTS_CARD_GUTTER_PX;
