import type { Branch } from './types';

const AUTO_GENERATED_CONDITION_LABEL_PATTERN = /^Condition(?: \d+)?(?: \(Copy\))?$/i;
export const CONDITION_NAME_FALLBACK = 'Condition';

export const CONDITION_QUESTION_PLACEHOLDER = 'Add the question this condition asks';

export const isAutoGeneratedConditionLabel = (label?: string): boolean => {
    const trimmedLabel = label?.trim() || '';
    if (!trimmedLabel) {
        return false;
    }

    return AUTO_GENERATED_CONDITION_LABEL_PATTERN.test(trimmedLabel);
};

export const getConditionQuestionLabel = (question?: string, legacyLabel?: string): string => {
    // Treat an explicit empty string as "intentionally blank" so the old label
    // does not keep resurfacing after a creator has split name vs question.
    if (question !== undefined) {
        return question.trim();
    }

    const trimmedLabel = legacyLabel?.trim() || '';
    if (!trimmedLabel) {
        return '';
    }

    if (isAutoGeneratedConditionLabel(trimmedLabel)) {
        return '';
    }

    return trimmedLabel;
};

export const materializeConditionQuestion = (question?: string, legacyLabel?: string): string => {
    if (question !== undefined) {
        return question;
    }

    return getConditionQuestionLabel(undefined, legacyLabel);
};

export const getConditionPathLabel = (
    branch: Pick<Branch, 'condition' | 'isDefault' | 'logic'>
): string => {
    const trimmedCondition = branch.condition?.trim();
    if (trimmedCondition) return trimmedCondition;
    if (!branch.isDefault) {
        const trimmedValue = branch.logic?.value !== undefined ? String(branch.logic.value).trim() : '';
        if (trimmedValue) return trimmedValue;
    }
    return branch.isDefault ? 'Fallback' : 'Untitled path';
};

export const getConditionRuleSummary = (
    branch: Pick<Branch, 'isDefault' | 'logic'>,
    variableFallback?: string
): string | null => {
    if (branch.isDefault) {
        return 'Used if nothing else matches';
    }

    const variable = branch.logic?.variable?.trim() || variableFallback?.trim() || '';
    if (!variable) {
        return null;
    }

    const value = branch.logic?.value !== undefined ? String(branch.logic.value).trim() : '';
    return `${variable} is ${value || 'value'}`;
};

export const getConditionSelectionLabel = (
    branch: Pick<Branch, 'condition' | 'isDefault' | 'logic'>,
    variableFallback?: string
): string => {
    const pathLabel = getConditionPathLabel(branch);
    if (branch.isDefault) {
        return `${pathLabel} (Fallback)`;
    }

    const ruleSummary = getConditionRuleSummary(branch, variableFallback);
    return ruleSummary ? `${pathLabel} (${ruleSummary})` : pathLabel;
};
