/**
 * VCA Design Tokens
 * 
 * Auto-generated from tokens3.json
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * To regenerate: npm run build:tokens
 */

export const vcaColors = {
  "vca-action": {
    "DEFAULT": "#0a66c2",
    "hover": "#004182",
    "active": "#004182",
    "disabled": "#0000004d",
    "background-action-transparent-hover": "#378fe91a",
    "background-action-transparent-active": "#378fe933"
  },
  "vca-text": {
    "DEFAULT": "#000000e5",
    "hover": "#000000e5",
    "active": "#000000e5",
    "meta": "#00000099",
    "meta-hover": "#000000e5",
    "meta-active": "#000000e5",
    "overlay": "#ffffff",
    "overlay-hover": "#ffffff",
    "overlay-active": "#ffffff",
    "disabled": "#0000004d",
    "negative": "#cb112d",
    "negative-hover": "#8a0015",
    "negative-active": "#640312",
    "positive": "#01754f",
    "positive-hover": "#004c33",
    "positive-active": "#004c33",
    "neutral": "#56687a",
    "neutral-hover": "#38434f",
    "neutral-active": "#38434f"
  },
  "vca-background": {
    "DEFAULT": "#ffffff",
    "neutral-soft": "#f4f2ee",
    "neutral-strong": "#eae6df",
    "offset": "#f4f2ee",
    "mobile-background-offset": "#eae6df",
    "knockout": "#ffffff",
    "knockout-hover": "#ffffff",
    "knockout-active": "#ffffff99",
    "disabled": "#8c8c8c33",
    "tint-soft": "#e8f3ff",
    "positive-strong": "#aff4dd",
    "positive-soft": "#d6faee",
    "negative-strong": "#ffdee3",
    "negative-soft": "#ffeef1",
    "transparent": "#ffffff00",
    "transparent-hover": "#8c8c8c1a",
    "transparent-active": "#8c8c8c33",
    "overlay": "#000000bf",
    "overlay-hover": "#000000e5",
    "overlay-active": "#000000e5"
  },
  "vca-border": {
    "DEFAULT": "#000000bf",
    "hover": "#000000e5",
    "active": "#000000e5",
    "faint": "#8c8c8c33",
    "faint-hover": "#8c8c8c4d",
    "faint-active": "#8c8c8c66",
    "subtle": "#0000004d",
    "subtle-hover": "#00000073",
    "subtle-active": "#00000073",
    "disabled": "#0000004d",
    "knockout": "#ffffff",
    "knockout-hover": "#ffffff"
  },
  "vca-surface": {
    "tint": "#f6fbff",
    "tint-hover": "#e8f3ff",
    "tint-active": "#e8f3ff"
  },
  "vca-link": {
    "DEFAULT": "#0a66c2",
    "hover": "#004182",
    "active": "#004182",
    "visited": "#8443ce",
    "visited-hover": "#592099",
    "visited-active": "#592099",
    "disabled": "#0000004d"
  },
  "vca-icon": {
    "DEFAULT": "#000000bf",
    "hover": "#000000e5",
    "active": "#000000e5",
    "disabled": "#0000004d",
    "knockout": "#ffffff",
    "knockout-hover": "#ffffff",
    "knockout-active": "#ffffff99"
  },
  "vca-label": {
    "DEFAULT": "#000000bf",
    "hover": "#000000e5",
    "active": "#000000e5",
    "disabled": "#0000004d",
    "knockout": "#ffffff",
    "knockout-hover": "#ffffff",
    "knockout-active": "#ffffff99"
  },
  "vca-positive": {
    "DEFAULT": "#01754f",
    "hover": "#004c33",
    "active": "#004c33"
  },
  "vca-negative": {
    "DEFAULT": "#cb112d",
    "hover": "#8a0015",
    "active": "#8a0015"
  },
  "vca-neutral": {
    "DEFAULT": "#56687a",
    "hover": "#38434f",
    "active": "#38434f"
  },
  "vca-premium": {
    "brand": "#f9c982",
    "text-brand": "#c37d16",
    "inbug": "#c37d16",
    "button-background": "#f9c982",
    "button-background-hover": "#e9a53f",
    "button-background-active": "#c37d16"
  },
  "vca-brand": {
    "logo-brand": "#0a66c2",
    "logo-mono": "#000000"
  },
  "vca-accent": {
    "4": "#56687a",
    "4-hover": "#38434f",
    "4-active": "#38434f"
  },
  "vca-shadow": "#0000004d",
  "vca-track": "#00000099",
  "vca-action-transparent": {
    "hover": "#378fe91a",
    "active": "#378fe933"
  },
  "vca-action-background-transparent": {
    "hover": "#378fe91a",
    "active": "#378fe933"
  },
  "vca-background-action-transparent": {
    "hover": "#378fe91a",
    "active": "#378fe933"
  },
  "vca-shadow-supplemental": "#8c8c8c33",
  "vca-white": "#ffffff",
  "vca-spec-orange": "#ED4400"
};

export const vcaColorsMeta = {
  "vca-action": {
    "DEFAULT": {
      "value": "#0a66c2",
      "ref": "{color.blue.blue-70}"
    },
    "hover": {
      "value": "#004182",
      "ref": "{color.blue.blue-80}"
    },
    "active": {
      "value": "#004182",
      "ref": "{color.blue.blue-80}"
    },
    "disabled": {
      "value": "#0000004d",
      "ref": "{color.black.black-a30}"
    },
    "background-action-transparent-hover": {
      "value": "#378fe91a",
      "ref": "{color.blue.blue-60-a10}"
    },
    "background-action-transparent-active": {
      "value": "#378fe933",
      "ref": "{color.blue.blue-60-a20}"
    }
  },
  "vca-text": {
    "DEFAULT": {
      "value": "#000000e5",
      "ref": "{color.black.black-a90}"
    },
    "hover": {
      "value": "#000000e5",
      "ref": "{color.black.black-a90}"
    },
    "active": {
      "value": "#000000e5",
      "ref": "{color.black.black-a90}"
    },
    "meta": {
      "value": "#00000099",
      "ref": "{color.black.black-a60}"
    },
    "meta-hover": {
      "value": "#000000e5",
      "ref": "{color.black.black-a90}"
    },
    "meta-active": {
      "value": "#000000e5",
      "ref": "{color.black.black-a90}"
    },
    "overlay": {
      "value": "#ffffff",
      "ref": "{color.white.white}"
    },
    "overlay-hover": {
      "value": "#ffffff",
      "ref": "{color.white.white}"
    },
    "overlay-active": {
      "value": "#ffffff",
      "ref": "{color.white.white}"
    },
    "disabled": {
      "value": "#0000004d",
      "ref": "{color.black.black-a30}"
    },
    "negative": {
      "value": "#cb112d",
      "ref": "{color.system-red.system-red-70}"
    },
    "negative-hover": {
      "value": "#8a0015",
      "ref": "{color.system-red.system-red-80}"
    },
    "negative-active": {
      "value": "#640312",
      "ref": "{color.system-red.system-red-90}"
    },
    "positive": {
      "value": "#01754f",
      "ref": "{color.system-green.system-green-70}"
    },
    "positive-hover": {
      "value": "#004c33",
      "ref": "{color.system-green.system-green-80}"
    },
    "positive-active": {
      "value": "#004c33",
      "ref": "{color.system-green.system-green-80}"
    },
    "neutral": {
      "value": "#56687a",
      "ref": "{color.cool-gray.cool-gray-70}"
    },
    "neutral-hover": {
      "value": "#38434f",
      "ref": "{color.cool-gray.cool-gray-80}"
    },
    "neutral-active": {
      "value": "#38434f",
      "ref": "{color.cool-gray.cool-gray-80}"
    }
  },
  "vca-background": {
    "DEFAULT": {
      "value": "#ffffff",
      "ref": "{color.white.white}"
    },
    "neutral-soft": {
      "value": "#f4f2ee",
      "ref": "{color.warm-gray.warm-gray-20}"
    },
    "neutral-strong": {
      "value": "#eae6df",
      "ref": "{color.warm-gray.warm-gray-30}"
    },
    "offset": {
      "value": "#f4f2ee",
      "ref": "{color.warm-gray.warm-gray-20}"
    },
    "mobile-background-offset": {
      "value": "#eae6df",
      "ref": "{color.warm-gray.warm-gray-30}"
    },
    "knockout": {
      "value": "#ffffff",
      "ref": "{color.white.white}"
    },
    "knockout-hover": {
      "value": "#ffffff",
      "ref": "{color.white.white}"
    },
    "knockout-active": {
      "value": "#ffffff99",
      "ref": "{color.white.white-a60}"
    },
    "disabled": {
      "value": "#8c8c8c33",
      "ref": "{color.system-gray.system-gray-60-a20}"
    },
    "tint-soft": {
      "value": "#e8f3ff",
      "ref": "{color.blue.blue-20}"
    },
    "positive-strong": {
      "value": "#aff4dd",
      "ref": "{color.system-green.system-green-30}"
    },
    "positive-soft": {
      "value": "#d6faee",
      "ref": "{color.system-green.system-green-20}"
    },
    "negative-strong": {
      "value": "#ffdee3",
      "ref": "{color.system-red.system-red-30}"
    },
    "negative-soft": {
      "value": "#ffeef1",
      "ref": "{color.system-red.system-red-20}"
    },
    "transparent": {
      "value": "#ffffff00",
      "ref": "{color.white.white-a0}"
    },
    "transparent-hover": {
      "value": "#8c8c8c1a",
      "ref": "{color.system-gray.system-gray-60-a10}"
    },
    "transparent-active": {
      "value": "#8c8c8c33",
      "ref": "{color.system-gray.system-gray-60-a20}"
    },
    "overlay": {
      "value": "#000000bf",
      "ref": "{color.black.black-a75}"
    },
    "overlay-hover": {
      "value": "#000000e5",
      "ref": "{color.black.black-a90}"
    },
    "overlay-active": {
      "value": "#000000e5",
      "ref": "{color.black.black-a90}"
    }
  },
  "vca-border": {
    "DEFAULT": {
      "value": "#000000bf",
      "ref": "{color.black.black-a75}"
    },
    "hover": {
      "value": "#000000e5",
      "ref": "{color.black.black-a90}"
    },
    "active": {
      "value": "#000000e5",
      "ref": "{color.black.black-a90}"
    },
    "faint": {
      "value": "#8c8c8c33",
      "ref": "{color.system-gray.system-gray-60-a20}"
    },
    "faint-hover": {
      "value": "#8c8c8c4d",
      "ref": "{color.system-gray.system-gray-60-a30}"
    },
    "faint-active": {
      "value": "#8c8c8c66",
      "ref": "{color.system-gray.system-gray-60-a40}"
    },
    "subtle": {
      "value": "#0000004d",
      "ref": "{color.black.black-a30}"
    },
    "subtle-hover": {
      "value": "#00000073",
      "ref": "{color.black.black-a45}"
    },
    "subtle-active": {
      "value": "#00000073",
      "ref": "{color.black.black-a45}"
    },
    "disabled": {
      "value": "#0000004d",
      "ref": "{color.black.black-a30}"
    },
    "knockout": {
      "value": "#ffffff",
      "ref": "{color.white.white}"
    },
    "knockout-hover": {
      "value": "#ffffff",
      "ref": "{color.white.white}"
    }
  },
  "vca-surface": {
    "tint": {
      "value": "#f6fbff",
      "ref": "{color.blue.blue-10}"
    },
    "tint-hover": {
      "value": "#e8f3ff",
      "ref": "{color.blue.blue-20}"
    },
    "tint-active": {
      "value": "#e8f3ff",
      "ref": "{color.blue.blue-20}"
    }
  },
  "vca-link": {
    "DEFAULT": {
      "value": "#0a66c2",
      "ref": "{color.blue.blue-70}"
    },
    "hover": {
      "value": "#004182",
      "ref": "{color.blue.blue-80}"
    },
    "active": {
      "value": "#004182",
      "ref": "{color.blue.blue-80}"
    },
    "visited": {
      "value": "#8443ce",
      "ref": "{color.purple.purple-70}"
    },
    "visited-hover": {
      "value": "#592099",
      "ref": "{color.purple.purple-80}"
    },
    "visited-active": {
      "value": "#592099",
      "ref": "{color.purple.purple-80}"
    },
    "disabled": {
      "value": "#0000004d",
      "ref": "{color.black.black-a30}"
    }
  },
  "vca-icon": {
    "DEFAULT": {
      "value": "#000000bf",
      "ref": "{color.black.black-a75}"
    },
    "hover": {
      "value": "#000000e5",
      "ref": "{color.black.black-a90}"
    },
    "active": {
      "value": "#000000e5",
      "ref": "{color.black.black-a90}"
    },
    "disabled": {
      "value": "#0000004d",
      "ref": "{color.black.black-a30}"
    },
    "knockout": {
      "value": "#ffffff",
      "ref": "{color.white.white}"
    },
    "knockout-hover": {
      "value": "#ffffff",
      "ref": "{color.white.white}"
    },
    "knockout-active": {
      "value": "#ffffff99",
      "ref": "{color.white.white-a60}"
    }
  },
  "vca-label": {
    "DEFAULT": {
      "value": "#000000bf",
      "ref": "{color.black.black-a75}"
    },
    "hover": {
      "value": "#000000e5",
      "ref": "{color.black.black-a90}"
    },
    "active": {
      "value": "#000000e5",
      "ref": "{color.black.black-a90}"
    },
    "disabled": {
      "value": "#0000004d",
      "ref": "{color.black.black-a30}"
    },
    "knockout": {
      "value": "#ffffff",
      "ref": "{color.white.white}"
    },
    "knockout-hover": {
      "value": "#ffffff",
      "ref": "{color.white.white}"
    },
    "knockout-active": {
      "value": "#ffffff99",
      "ref": "{color.white.white-a60}"
    }
  },
  "vca-positive": {
    "DEFAULT": {
      "value": "#01754f",
      "ref": "{color.system-green.system-green-70}"
    },
    "hover": {
      "value": "#004c33",
      "ref": "{color.system-green.system-green-80}"
    },
    "active": {
      "value": "#004c33",
      "ref": "{color.system-green.system-green-80}"
    }
  },
  "vca-negative": {
    "DEFAULT": {
      "value": "#cb112d",
      "ref": "{color.system-red.system-red-70}"
    },
    "hover": {
      "value": "#8a0015",
      "ref": "{color.system-red.system-red-80}"
    },
    "active": {
      "value": "#8a0015",
      "ref": "{color.system-red.system-red-80}"
    }
  },
  "vca-neutral": {
    "DEFAULT": {
      "value": "#56687a",
      "ref": "{color.cool-gray.cool-gray-70}"
    },
    "hover": {
      "value": "#38434f",
      "ref": "{color.cool-gray.cool-gray-80}"
    },
    "active": {
      "value": "#38434f",
      "ref": "{color.cool-gray.cool-gray-80}"
    }
  },
  "vca-premium": {
    "brand": {
      "value": "#f9c982",
      "ref": "{color.amber.amber-40}"
    },
    "text-brand": {
      "value": "#c37d16",
      "ref": "{color.amber.amber-60}"
    },
    "inbug": {
      "value": "#c37d16",
      "ref": "{color.amber.amber-60}"
    },
    "button-background": {
      "value": "#f9c982",
      "ref": "{color.amber.amber-40}"
    },
    "button-background-hover": {
      "value": "#e9a53f",
      "ref": "{color.amber.amber-50}"
    },
    "button-background-active": {
      "value": "#c37d16",
      "ref": "{color.amber.amber-60}"
    }
  },
  "vca-brand": {
    "logo-brand": {
      "value": "#0a66c2",
      "ref": "{color.blue.blue-70}"
    },
    "logo-mono": {
      "value": "#000000",
      "ref": "{color.black.black-a100}"
    }
  },
  "vca-accent": {
    "4": {
      "value": "#56687a",
      "ref": "{color.cool-gray.cool-gray-70}"
    },
    "4-hover": {
      "value": "#38434f",
      "ref": "{color.cool-gray.cool-gray-80}"
    },
    "4-active": {
      "value": "#38434f",
      "ref": "{color.cool-gray.cool-gray-80}"
    }
  },
  "vca-shadow": {
    "value": "#0000004d",
    "ref": "{color.black.black-a30}"
  },
  "vca-track": {
    "value": "#00000099",
    "ref": "{color.black.black-a60}"
  },
  "vca-action-transparent": {
    "hover": {
      "value": "#378fe91a",
      "ref": "{color.blue.blue-60-a10}"
    },
    "active": {
      "value": "#378fe933",
      "ref": "{color.blue.blue-60-a20}"
    }
  },
  "vca-action-background-transparent": {
    "hover": {
      "value": "#378fe91a",
      "ref": "{color.blue.blue-60-a10}"
    },
    "active": {
      "value": "#378fe933",
      "ref": "{color.blue.blue-60-a20}"
    }
  },
  "vca-background-action-transparent": {
    "hover": {
      "value": "#378fe91a",
      "ref": "{color.blue.blue-60-a10}"
    },
    "active": {
      "value": "#378fe933",
      "ref": "{color.blue.blue-60-a20}"
    }
  },
  "vca-shadow-supplemental": {
    "value": "#8c8c8c33",
    "ref": "{color.system-gray.system-gray-60-a20}"
  },
  "vca-white": {
    "value": "#ffffff",
    "ref": "{color.white.white-100}"
  },
  "vca-spec-orange": {
    "value": "#ED4400",
    "ref": "{color.spec-orange}"
  }
};

export const vcaSpacing = {
  "vca-none": "0px",
  "vca-xs": "4px",
  "vca-s": "8px",
  "vca-md": "12px",
  "vca-lg": "16px",
  "vca-xl": "20px",
  "vca-xxl": "24px"
};

export const vcaSpacingMeta = {
  "vca-none": {
    "value": 0,
    "unit": "px",
    "ref": 0
  },
  "vca-xs": {
    "value": 4,
    "unit": "px",
    "ref": "{spacing.0}"
  },
  "vca-s": {
    "value": 8,
    "unit": "px",
    "ref": "{spacing.1}"
  },
  "vca-md": {
    "value": 12,
    "unit": "px",
    "ref": "{spacing.2}"
  },
  "vca-lg": {
    "value": 16,
    "unit": "px",
    "ref": "{spacing.3}"
  },
  "vca-xl": {
    "value": 20,
    "unit": "px",
    "ref": "{spacing.4}"
  },
  "vca-xxl": {
    "value": 24,
    "unit": "px",
    "ref": "{spacing.5}"
  }
};

export const vcaRadius = {
  "vca-none": "0px",
  "vca-xs": "4px",
  "vca-sm": "8px",
  "vca-md": "16px",
  "vca-lg": "24px",
  "vca-xl": "32px",
  "vca-xxl": "48px",
  "vca-round": "360px"
};

export const vcaRadiusMeta = {
  "vca-none": {
    "value": 0,
    "unit": "px",
    "ref": 0
  },
  "vca-xs": {
    "value": 4,
    "unit": "px",
    "ref": "{radius.xs}"
  },
  "vca-sm": {
    "value": 8,
    "unit": "px",
    "ref": "{radius.sm}"
  },
  "vca-md": {
    "value": 16,
    "unit": "px",
    "ref": "{radius.md}"
  },
  "vca-lg": {
    "value": 24,
    "unit": "px",
    "ref": "{radius.lg}"
  },
  "vca-xl": {
    "value": 32,
    "unit": "px",
    "ref": "{radius.xl}"
  },
  "vca-xxl": {
    "value": 48,
    "unit": "px",
    "ref": "{radius.xxl}"
  },
  "vca-round": {
    "value": 360,
    "unit": "px",
    "ref": "{radius.round}"
  }
};
