import { useState } from 'react';
import { Message } from '@/components/vca-components/messages/Message';
import { DemoSection } from '@/components/component-library/DemoSection';
import { ToggleButtons, FormTextarea, FormCheckbox } from '@/components/component-library/DemoControls';

const MessageComponentView = () => {
  // Interactive demo state
  const [type, setType] = useState<'ai' | 'user' | 'human-agent' | 'disclaimer'>('ai');
  const [text, setText] = useState('This is a sample message');
  const [errorFeedback, setErrorFeedback] = useState(false);

  // Determine which text prop to use based on type
  const getTextProps = () => {
    switch (type) {
      case 'ai':
        return { defaultText: text };
      case 'user':
        return { userText: text };
      case 'human-agent':
        return { humanAgentText: text };
      case 'disclaimer':
        return {}; // disclaimer uses fixed text
      default:
        return { defaultText: text };
    }
  };

  return (
    <div className="pt-16">
      <h1 className="mb-2">Message</h1>
      <p className="text-md text-gray-500 mb-12">Display AI, user, human agent, and disclaimer messages in the chatbot interface.</p>
      
      {/* Demo Section */}
      <DemoSection
        controls={
          <div className="grid grid-cols-2 gap-x-8 gap-y-4">
            <ToggleButtons
              label="Type"
              options={['ai', 'user', 'human-agent', 'disclaimer'] as const}
              value={type}
              onChange={setType}
            />

            <FormCheckbox
              id="errorFeedback"
              label="Show Error (User only)"
              checked={errorFeedback}
              onCheckedChange={setErrorFeedback}
              disabled={type !== 'user'}
            />

            {type !== 'disclaimer' && (
              <FormTextarea
                id="text"
                label="Message Text"
                value={text}
                onChange={(e) => setText(e.target.value)}
                placeholder="Enter message..."
                rows={3}
                className="col-span-2"
              />
            )}
          </div>
        }
      >
        <div className="w-[352px] mx-auto px-vca-xxl">
          <Message 
            type={type}
            {...getTextProps()}
            errorFeedback={type === 'user' ? errorFeedback : undefined}
          />
        </div>
      </DemoSection>

      {/* Usage Section */}
      <div className="mt-16">
        <h2 className="mb-8">Usage</h2>
        
        <div className="space-y-12">
          <div>
            <h3 className="mb-4">AI message</h3>
            <p className="text-sm text-gray-500 mb-3">Messages generated by AI agent are basic with minimal styling.</p>
            <div className="bg-white border border-gray-200 rounded-lg p-4">
              <div className="px-vca-xxl">
                <Message type="ai" defaultText="Hi there. With the help of AI, I can answer questions about administration or connect you to someone who can." />
              </div>
            </div>
          </div>

          <div>
            <h3 className="mb-4">Disclaimer</h3>
            <p className="text-sm text-gray-500 mb-3">Legal disclaimer text displayed at the start of conversations.</p>
            <div className="bg-white border border-gray-200 rounded-lg p-4">
              <div className="px-vca-xxl">
                <Message type="disclaimer" />
              </div>
            </div>
          </div>

          <div>
            <h3 className="mb-4">User message</h3>
            <p className="text-sm text-gray-500 mb-3">User-submitted messages are displayed on the right side with a subtle surface color.</p>
            <div className="bg-white border border-gray-200 rounded-lg p-4">
              <div className="px-vca-xxl">
                <Message type="user" userText="Why was my contest campaign rejected if it falls within Linkedin Contest guidelines? I need that campaign to be running." />
              </div>
            </div>
          </div>

          <div>
            <h3 className="mb-4">User message with error</h3>
            <p className="text-sm text-gray-500 mb-3">Failed user messages show an error indicator and retry action.</p>
            <div className="bg-white border border-gray-200 rounded-lg p-4">
              <div className="px-vca-xxl">
                <Message type="user" userText="This message failed to send" errorFeedback={true} />
              </div>
            </div>
          </div>

          <div>
            <h3 className="mb-4">Support agent message</h3>
            <p className="text-sm text-gray-500 mb-3">Human support agent messages with contain an avatar, name, and timestamp.</p>
            <div className="bg-white border border-gray-200 rounded-lg p-4">
              <div className="px-vca-xxl">
                <Message type="human-agent" humanAgentText="Hi Nick, how can I help?" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default MessageComponentView;

