export const CONNECTION_PREVIEW_CARD_WIDTH_PX = 152;
export const CONNECTION_PREVIEW_CARD_HEIGHT_PX = 78;
export const CONNECTION_PREVIEW_DRAG_CARD_OFFSET_X_PX = 16;
export const CONNECTION_PREVIEW_HOVER_CARD_OFFSET_X_PX = 95;
